Models/GameViewModels/CancelArmyMovementViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebGame.Models.GameViewModels
{
    public class CancelArmyMovementViewModel
    {
        public int Id { get; set; }
        public int WorldId { get; set; }
        public int AttackerPlayerId { get; set; }
        public int TargetTowerId { get; set; }
        public int Amount { get; set; }
        public int RoundsToArrive { get; set; }
        public int AccountId { get; set; }
        public bool ReturnBase { get; set; }
        public string TowerName { get; set; }

    }
}

Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebGame.Models.GameViewModels;
using WebGame.Models.WebGame;
using WebGame.ViewModel;

namespace WebGame.Controllers
{
    public class GameController : Controller
    {
        private readonly webgameContext _context;

        public GameController(webgameContext context)
        {
            _context = context;
        }

        [HttpGet("Game/MainGameRazor/{error}/{player1Id}/{player2Id}/{worldId}/{accountCheck}")]
        public async Task<IActionResult> MainGameRazor(int accountCheck, int player1Id, int player2Id, int? worldId, int? error) // DÜNAAMILINE VERSIOON MainGame lehest
        {
            if (!User.Identity.IsAuthenticated) // Kas kasutaja on sisselogitud
            {
                return RedirectToAction(nameof(Tutorial));
            }

            var world = _context.World
                .FirstOrDefault(m => m.WorldId == worldId);

            // Security
            if (world.Player1IdAcc != (Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier))) && world.Player2IdAcc != (Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier))))
            {
                return RedirectToAction("SelectGame", "Game");
            }
            if (world.GameFinished == true)
            {
                return RedirectToAction("SelectGame", "Game");
            }

            if (error == 1)
            {
                ViewBag.Error = "You don't have enough money to upgrade this tower!";
            }

            ViewBag.WorldId = worldId;

            ViewBag.Player1Id = player1Id;
            ViewBag.Player2Id = player2Id;
            if (world.Player1IdAcc == (Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier))))
            {
                var enemyName = _context.Playeraccount.FirstOrDefault(m => m.AccountId == world.Player2IdAcc);
                // Kui nimi on liiga pikk
                if (enemyName.AccountName.Length > 5)
                {
                    ViewBag.EnemyName = enemyName.AccountName.Substring(0, 5) + "...";
                }
                else
                {
                    ViewBag.EnemyName = enemyName.AccountName;
                }
                ViewBag.EnemyId = enemyName.AccountId;
                var yourName = _context.Playeraccount.FirstOrDefault(m => m.AccountId == world.Player1IdAcc);

                // Kui nimi on liiga pikk
                if (yourName.AccountName.Length > 5)
                {
                    ViewBag.YourName = yourName.AccountName.Substring(0, 5) + "...";
                }
                else
                {
                    ViewBag.YourName = yourName.AccountName;
                }
                ViewBag.YourId = yourName.AccountId;
            }
            else
            {
                var enemyName = _context.Playeraccount.FirstOrDefault(m => m.AccountId == world.Player1IdAcc);
                if (enemyName.AccountName.Length > 5)
                {
                    ViewBag.EnemyName = enemyName.AccountName.Substring(0, 5) + "...";
                }
                else
                {
                    ViewBag.EnemyName = enemyName.AccountName;
                }
                ViewBag.EnemyId = enemyName.AccountId;

                var yourName = _context.Playeraccount.FirstOrDefault(m => m.AccountId == world.Player2IdAcc);
                if (yourName.AccountName.Length > 5)
                {
                    ViewBag.YourName = yourName.AccountName.Substring(0, 5) + "...";
                }
                else
                {
                    ViewBag.YourName = yourName.AccountName;
                }
                ViewBag.YourId = yourName.AccountId;
            }

            if (world.GameFinished == true)
            {
                var PlayeraccountNameWin = _context.Playeraccount.FirstOrDefault(m => m.AccountId == world.WinnerAccountId);
                ViewBag.Winner = "Player " + PlayeraccountNameWin.AccountName + " won the game!";
                ViewBag.IsWinner = true;
            }

            var playerIdWhoClicks = (from d in _context.Player where d.WorldId == worldId && d.AccountId == (Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier))) select d.PlayerId).FirstOrDefault();

            ViewBag.PlayerIdWhoClicks = playerIdWhoClicks;

            if (playerIdWhoClicks == player1Id) // SignalR dünaamilise uuenduse jaoks vaja
            {
                ViewBag.EnemyPlayerId = player2Id;
            }
            else
            {
                ViewBag.EnemyPlayerId = player1Id;
            }

            var findPlayerGold = (from d in _context.Player where d.PlayerId == playerIdWhoClicks && d.WorldId == worldId select d.Gold).FirstOrDefault();

            ViewBag.FindPlayerGold = findPlayerGold;

            var loggedInPlayerTowers = (from d in _context.Tower where d.Owner == playerIdWhoClicks && d.WorldId == worldId select d).ToList();

            int peopleGrowingPlusPeopleAlive = 0;
            int peopleGrowing = 0;
            int peopleNow = 0;
            int goldForTowers = 0;
            foreach (var tower in loggedInPlayerTowers)
            {
                float? peopleGrowingPercentage = (100 + tower.TowerLvl) / 100f;
                float? peopleGrown = peopleGrowingPercentage * tower.Attack;
                peopleNow += tower.Attack;
                peopleGrowing += Convert.ToInt32(peopleGrown) - tower.Attack;
                peopleGrowingPlusPeopleAlive += Convert.ToInt32(peopleGrown);
                goldForTowers += 10;
            }
            ViewBag.GoldForTowers = goldForTowers;
            ViewBag.PeopleNow = peopleNow;
            ViewBag.PeopleGrowing = peopleGrowing;
            ViewBag.PeopleGrowingSum = peopleGrowingPlusPeopleAlive;

            ViewBag.WorldId = worldId;

            var playerIds = (from d in _context.Player where d.AccountId == (Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier))) select d.PlayerId).ToList();

            // Saada mängijatele teavitus, kumb neist on valmis
            if (world.Player1Ready == true ^ world.Player2Ready == true) // Kui ainult üks mängijatest on valmis
            {
                if (playerIds.Contains(player1Id) && world.Player1Id == player1Id && world.Player1Ready == true)
                {
                    ViewBag.You = "YOU ARE READY";
                    ViewBag.Enemy = "ENEMY IS NOT READY";
                }
                else if (!playerIds.Contains(player1Id) && world.Player1Id == player1Id && world.Player1Ready == true)
                {
                    ViewBag.You = "YOU ARE NOT READY";
                    ViewBag.Enemy = "ENEMY IS READY";
                }
                else if (playerIds.Contains(player2Id) && world.Player2Id == player2Id && world.Player2Ready == true)
                {
                    ViewBag.You = "YOU ARE READY";
                    ViewBag.Enemy = "ENEMY IS NOT READY";
                }
                else if (!playerIds.Contains(player2Id) && world.Player2Id == player2Id && world.Player2Ready == true)
                {
                    ViewBag.You = "YOU ARE NOT READY";
                    ViewBag.Enemy = "ENEMY IS READY";
                }
            }
            else if (world.Player1Ready == false && world.Player2Ready == false) // Kontrolli, kas mõlemad mängijad pole valmis
            {
                ViewBag.You = "YOU ARE NOT READY";
                ViewBag.Enemy = "ENEMY IS NOT READY";
            }
            else if (world.Player1Ready == true && world.Player2Ready == true) // Kontrolli, kas mõlemad mängijad on valmis
            {
                world.Player1Ready = false;
                world.Player2Ready = false;
                _context.Update(world);
                _context.SaveChanges();
            }

            var towers = await (from ep in _context.Tower
                                join e in _context.World on ep.WorldId equals e.WorldId
                                where e.WorldId == worldId
                                select new TowerViewModel
                                {
                                    Id = ep.TowerId,
                                    Owner = ep.Owner,
                                    TowerId = ep.TowerId,
                                    Attack = ep.Attack,
                                    Defence = ep.Defence,
                                    WorldId = e.WorldId,
                                    Player1Id = e.Player1Id,
                                    Player2Id = e.Player2Id,
                                    Player1Ready = e.Player1Ready,
                                    Player2Ready = e.Player2Ready,
                                    TowerLvl = ep.TowerLvl,
                                    TowerName = ep.TowerName
                                }).ToListAsync();

            ViewBag.Towers = towers;
            return View(towers);
        }

        [HttpGet("Game/Profile/{accountId}")]
        public async Task<IActionResult> Profile(int accountId)
        {
            var profile = (from d in _context.Playeraccount where d.AccountId == accountId select d).FirstOrDefault();

            ViewBag.Name = profile.AccountName;
            ViewBag.Wins = profile.Wins;
            ViewBag.Losts = profile.Losts;

            if (profile.Wins > 0 && profile.Losts < 1)
            {
                ViewBag.WinRate = profile.Wins * 100;
            }
            else
            {
                ViewBag.WinRate = (float)System.Math.Round(((float)profile.Wins / (profile.Wins + profile.Losts)) * 100, 2); // Ainult 2 numbrit peale koma
            }
            return View();
        }

ViewComponents/OverallStatsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WebGame.Models.GameViewModels;
using WebGame.Models.WebGame;



namespace WebGame.ViewComponents
{
    public class OverallStatsViewComponent : ViewComponent
    {
        private readonly webgameContext _context;

        public OverallStatsViewComponent(webgameContext context)
        {
            _context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync(
           int playerId, int worldId)
        {
            var findPlayerGold = (from d in _context.Player
                                  where d.PlayerId == playerId && d.WorldId == worldId
                                  select d.Gold).FirstOrDefault();

            ViewBag.FindPlayerGold = findPlayerGold;

            var towersSum = (from d in _context.Tower
                             where d.Owner == playerId && d.WorldId == worldId
                             select d).ToList();

            int peopleNow = 0;
            int peopleGrowing = 0;
            int goldForTowers = 0;
            foreach (var tower in towersSum)
            {
                float? peopleGrowingPercentage = (100 + tower.TowerLvl) / 100f;
                float? peopleGrowed = peopleGrowingPercentage * tower.Attack;
                peopleNow += tower.Attack;
                peopleGrowing += Convert.ToInt32(peopleGrowed) - tower.Attack;
                goldForTowers += 10;

            }
            ViewBag.PeopleNow = peopleNow;
            if (peopleGrowing > 0)
                ViewBag.PeopleGrowing = " + People Growing (" + peopleGrowing + ")";
            ViewBag.goldForTowers = goldForTowers;

            var soonReturns = (from d in _context.AttDef
                               where d.AttackerPlayerId == playerId && d.WorldId == worldId && d.ReturnBase == true
                               select d.Amount).ToList();

            int soonReturning = 0;
            foreach (var att in soonReturns)
            {
                soonReturning += att;
            }
            if (soonReturning > 0)
                ViewBag.SoonReturning = " + Army returning sometime (" + soonReturning + ")";

            string view = "OverallStats";

            return View(view);
        }

    }
}

Views/Game/CancelArmyMovement.cshtml
@model IEnumerable<WebGame.Models.WebGame.AttDef>

@using System;
@using System.Collections.Generic;
@using System.Security.Claims;

@{
    ViewData["Title"] = "CancelArmyMovement";
    var towerNames = ViewBag.TowerNames;
    int counter = 0;
}

<div>
    @await Component.InvokeAsync("OverallStats", new { worldId = ViewBag.WorldId, playerId = ViewBag.PlayerIdWhoClicks })
</div>
<br />

<h1 style="font-size:30px;" class="btn btn-danger nav-link text-white">Movements</h1>


@{
    if (ViewBag.Empty == true)
    {
        <h1 class="Empty">You don't have any army to stop</h1>
        <a class="btn btn-info" asp-area="" asp-route-error="0" asp-route-player1Id="@ViewBag.Player1Id" asp-route-player2Id="@ViewBag.Player2Id" asp-route-worldId="@ViewBag.WorldId" asp-route-accountCheck="@Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier))" asp-controller="Game" asp-action="MainGameRazor">Back to map</a>

    }
    else
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Destination
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Amount)
                    </th>
                    <th>
                        Rounds to arrive 
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @towerNames[counter]
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Amount)
                        </td>
                        <td>

                            @if (item.RoundsToArrive == 0)
                            {
                                <p>Next round</p>
                            }
                            else
                            {
                                @(Convert.ToInt32(item.RoundsToArrive + 1))// Lisa number 1 RoundsToArrive muutujale, kuna siis on seda lihtsam lugeda tavakasutajal

                            }

                        </td>
                        <td>
                            <a class="btn btn-warning" asp-action="CancelArmyMovement_" asp-route-accountCheck="@Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier))" asp-route-id="@item.Id" asp-route-worldId="@item.WorldId" asp-route-owner="@item.AttackerPlayerId" asp-route-player1Id="@ViewBag.Player1Id" asp-route-player2Id="@ViewBag.Player2Id">Cancel</a>
                        </td>
                    </tr>
                    counter++;
                }
            </tbody>
        </table>
        <div>
            <a class="btn btn-info" asp-area="" asp-route-error="0" asp-route-player1Id="@ViewBag.Player1Id" asp-route-player2Id="@ViewBag.Player2Id" asp-route-worldId="@ViewBag.WorldId" asp-route-accountCheck="@Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier))" asp-controller="Game" asp-action="MainGameRazor">Back to map</a>
        </div>
    }
}

<style>
    .Empty {
        color: red;
    }

    .btn-container, .container {
        background-color: white;
        border-radius: 4px;
        margin-bottom: 40px;
    }
</style>

Views/Game/MainGame.cshtml
@model IEnumerable<WebGame.ViewModel.TowerViewModel>

@using System;
@using System.Collections.Generic;
@using System.Linq;
@using System.Threading.Tasks;
@using Microsoft.AspNetCore.Mvc;
@using Microsoft.EntityFrameworkCore;
@using WebGame.Models.WebGame;
@using WebGame.ViewModel;
@using System.Security.Claims;
@{
    ViewData["Title"] = "MainGame";

    var you = ViewBag.You;
    var enemy = ViewBag.Enemy;
}

@await Component.InvokeAsync("OverallStats", new { worldId = ViewBag.WorldId, playerId = ViewBag.PlayerIdWhoClicks })

<div class="OverallStats">
    @{
        if (ViewBag.IsWinner != true)
        {
            <h1 class="ReadyLBL">
                @{
                    if (you.Contains("NOT"))
                    {
                        <span class="NOT">@you</span> <a class="white">-|-</a>
                    }
                    else
                    {
                        @you <a class="white">-|-</a>
                    }
                    if (enemy.Contains("NOT"))
                    {
                        <span class="NOT">@enemy</span>
                    }
                    else
                    {
                        @enemy
                    }
                }

            </h1>
            <div class="buttons">
                <div class="content-3d Ready">
                    <a asp-action="PlayerReady" asp-route-worldId="@ViewBag.WorldId" class="btn-3d green">Ready</a>
                </div>

                <div class="content-3d CancelArmyMovement">
                    <a asp-action="CancelArmyMovement" asp-route-worldId="@ViewBag.WorldId" asp-route-PlayerIdWhoClicks="@ViewBag.PlayerIdWhoClicks" asp-route-player1Id="@ViewBag.Player1Id" asp-route-player2Id="@ViewBag.Player2Id" class="btn-3d red">Movements</a>
                </div>
            </div>
        }
        else
        {
            <h2>WINNER</h2>
            <h1>@ViewBag.Winner</h1>
            <h2>WINNER</h2>
        }
    }
</div>
<div class="Stats1">
    <a>
        <a class="PlayerNames btn btn-primary" asp-area="" asp-route-AccountId="@ViewBag.YourId" asp-controller="Game" asp-action="Profile">@ViewBag.YourName</a>
        VS
        <a class="PlayerNames btn btn-primary" asp-area="" asp-route-AccountId="@ViewBag.EnemyId" asp-controller="Game" asp-action="Profile">@ViewBag.EnemyName</a>
    </a>
    <br />
    @{
        if (@ViewBag.Error != null)
        {
            <div class="alert alert-danger Error" role="alert">  @ViewBag.Error</div>
        }
    }
</div>


<div class="wrapper">
    @{
        int counter = 0;
        string towerOwnerColor = "";
    }
    @foreach (var item in Model)
    {
        counter++;
        string box = "box" + counter;
        if (item.Owner == ViewBag.PlayerIdWhoClicks)
        {
            towerOwnerColor = "friendly";
        }
        else if (item.Owner == 0)
        {
            towerOwnerColor = "empty";
        }
        else
        {
            towerOwnerColor = "enemy";
        }
        <div class="@box @towerOwnerColor">
            <h5> @Html.DisplayFor(modelItem => item.TowerName)</h5>
            <a class="btn btn-danger" asp-action="CreateArmyMission" asp-route-playerIdWhoClicks="@ViewBag.PlayerIdWhoClicks" asp-route-Owner="@item.Owner" asp-route-WorldId="@item.WorldId" asp-route-SelectedTower="@item.TowerId" asp-route-player1Id="@item.Player1Id" asp-route-player2Id="@item.Player2Id">Move</a>


            @{ if (item.Owner == ViewBag.PlayerIdWhoClicks)
                {
                    int TowerLvl = item.TowerLvl;
                    int Defence = (item.TowerLvl) * 5;
                    int costs = (item.TowerLvl + 1) * 100;
                    int nxtTowerLvl = item.TowerLvl + 1;
                    int nxtDefence = (item.TowerLvl + 1) * 5;
                    <br />
                    <span>Size: <a style="font-size:20px; color:red;"> @Html.DisplayFor(modelItem => item.Attack)</a></span>
                    <a class="btn btn-success" asp-action="UpgradeTower" asp-route-id="@item.TowerId" asp-route-accountId="@Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier))" asp-route-owner="@item.Owner" asp-route-player1Id="@item.Player1Id" asp-route-player2Id="@item.Player2Id" asp-route-worldId="@item.WorldId">Upgrade tower</a>
                    <br />

                    <a class="upgrade">Costs: @costs</a>
                    <br />
                    <a class="upgrade">Lvl: @item.TowerLvl -> @nxtTowerLvl</a>
                    <br />
                    <a class="upgrade">Def: @Defence -> @nxtDefence</a>
                    <br />
                    <a class="upgrade">Borns: @item.TowerLvl% -> @nxtTowerLvl% </a>
                }
            }
        </div>
    }
</div>

<style>

    .upgrade {
        font-size: 17px;
    }

    .buttons {
        margin-left: 200px;
        text-align: center;
        margin-top: -15px;
    }

    .Ready {
        width: 50%;
        height: 0px;
    }

    .CancelArmyMovement {
        width: 120%;
        height: 0px; /* Siis tulevad mängija nimed üksteise kõrvale*/
    }

    @@media (max-width:991px) {
        .Ready {
            width: 30%;
        }

        .CancelArmyMovement {
            width: 130%;
        }
    }

    @@media (max-width: 767px) {
        .Ready {
            width: 10%;
        }

        .CancelArmyMovement {
            width: 200%;
        }
    }


    .btn-container, .container {
        background-color: white;
        border-radius: 4px;
        margin-bottom: 40px;
    }

    .btn-3d {
        position: relative;
        display: inline-block;
        font-size: 22px;
        padding: 20px 60px;
        color: white;
        margin: 20px 10px 10px;
        border-radius: 6px;
        text-align: center;
        transition: top .01s linear;
        text-shadow: 0 1px 0 rgba(0,0,0,0.15);
    }

        .btn-3d.green:hover {
            background-color: #87a86f;
        }

    .color .green {
        background: #82c8a0;
    }


    .btn-3d:active {
        top: 9px;
    }


    .btn-3d.green {
        background-color: #82c8a0;
        box-shadow: 0 0 0 1px #82c8a0 inset, 0 0 0 2px rgba(255,255,255,0.15) inset, 0 8px 0 0 rgba(126, 194, 155, .7), 0 8px 0 1px rgba(0,0,0,.4), 0 8px 8px 1px rgba(0,0,0,0.5);
    }

        .btn-3d.green:active {
            box-shadow: 0 0 0 1px #82c8a0 inset, 0 0 0 2px rgba(255,255,255,0.15) inset, 0 0 0 1px rgba(0,0,0,0.4);
        }

    .btn.green {
        box-shadow: 0px 4px 0px #87a86f;
    }

        .btn.green:active {
            box-shadow: 0 0 #87a86f;
            background-color: #87a86f;
        }

    .btn.green, .btn-two.green {
        background-color: #9abf7f;
    }

    .btn-gradient.green {
        background: rgba(130,200,160,1);
        background: -moz-linear-gradient(top, rgba(130,200,160,1) 0%, rgba(130,199,158,1) 100%);
        background: -webkit-gradient(left top, left bottom, color-stop(0%, rgba(130,200,160,1)), color-stop(100%, rgba(130,199,158,1)));
        background: -webkit-linear-gradient(top, rgba(130,200,160,1) 0%, rgba(130,199,158,1) 100%);
        background: -o-linear-gradient(top, rgba(130,200,160,1) 0%, rgba(130,199,158,1) 100%);
        background: -ms-linear-gradient(top, rgba(130,200,160,1) 0%, rgba(130,199,158,1) 100%);
        background: linear-gradient(to bottom, rgba(130,200,160,1) 0%, rgba(124, 185, 149, 1) 100%);
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#82c8a0', endColorstr='#82c79e', GradientType=0 );
    }

        .btn-gradient.green:active {
            background: #72B08E;
        }

    .btn.red, .btn-two.red {
        background-color: #fa5a5a;
    }

    .btn-3d.red:hover {
        background-color: #ff4c4b;
    }

    .btn-3d.red {
        background-color: #e74c3c;
        box-shadow: 0 0 0 1px #c63702 inset, 0 0 0 2px rgba(255,255,255,0.15) inset, 0 8px 0 0 #C24032, 0 8px 0 1px rgba(0,0,0,0.4), 0 8px 8px 1px rgba(0,0,0,0.5);
    }

        .btn-3d.red:active {
            box-shadow: 0 0 0 1px #c63702 inset, 0 0 0 2px rgba(255,255,255,0.15) inset, 0 0 0 1px rgba(0,0,0,0.4);
        }

    .btn.red {
        box-shadow: 0px 4px 0px #E04342;
    }

        .btn.red:active {
            box-shadow: 0 0 #ff4c4b;
            background-color: #ff4c4b;
        }


    .Error {
        top: 20px;
        font-size: 20px;
        left: 0px;
        margin-right: 160px;
    }

    .PlayerNames {
        font-size: 35px;
        color: mediumspringgreen;
        background-color: black;
        z-index: 1;
    }

    .Stats1 {
        font-size: 30px;
        left: 5%;
        right: 70%;
        top: 30px;
        position: fixed;
        z-index: 1;
    }

    @@media (max-width:1588px) {
        .Stats1 {
            font-size: 20px;
            margin-left: -1%;
        }
    }



    body {
        font-size: 100%;
    }

    .ReadyLBL {
        font-size: 30px;
        color: chartreuse;
        background-color: black;
        top: 50px;
        left: 60%;
        position: fixed;
        z-index: 1;
    }

    @@media (max-width:1588px) {
        .ReadyLBL {
            font-size: 23px;
            top: 52px;
        }
    }

    @@media (max-width:1180px) {
        .ReadyLBL {
            font-size: 20px;
            top: 52px;
        }
    }

    @@media (max-width:976px) {
        .ReadyLBL {
            font-size: 20px;
        }
    }

    .NOT {
        color: red;
    }

    .white {
        color: white !important;
    }

    .OverallStats {
        left: 26%;
    }

    .ReadyBTN {
        font-size: 40px;
        color: green;
        margin-right: 7%;
    }

    .CancelArmyMovementBTN {
        font-size: 40px;
        color: red;
    }


    * {
        box-sizing: border-box;
    }

    .wrapper {
        border: 2px solid #f76707;
        border-radius: 50px;
        background-color: #fff4e6;
        display: grid;
        grid-template-columns: repeat(8, 185px); /* 12.5%*/
        grid-template-rows: repeat(3, 260px); /* 225*/
        width: 1480px; /*90%*/
        position: absolute;
        left: 50%;
        top: 577px;
        transform: translate(-50%, -50%);
    }

        .wrapper > .friendly {
            border: 2px solid #ffa94d;
            border-radius: 10px;
            background-color: lightgreen;
            padding: 1em;
            color: black;
        }

        .wrapper > .enemy {
            border: 2px solid #ffa94d;
            border-radius: 10px;
            background-color: lightcoral;
            padding: 1em;
            color: black;
        }

        .wrapper > .empty {
            border: 2px solid #ffa94d;
            border-radius: 10px;
            background-color: grey;
            padding: 1em;
            color: black;
        }


    .box1 {
        grid-column-start: 1;
        grid-row-start: 2;
    }

    .box2 {
        grid-column-start: 2;
        grid-row-start: 0;
    }

    .box3 {
        grid-column-start: 2;
        grid-row-start: 2;
    }

    .box4 {
        grid-column-start: 2;
        grid-row-start: 3;
    }

    .box5 {
        grid-column-start: 3;
        grid-row-start: 1;
    }

    .box6 {
        grid-column-start: 3;
        grid-row-start: 2;
    }

    .box7 {
        grid-column-start: 3;
        grid-row-start: 3;
    }

    .box8 {
        grid-column-start: 4;
        grid-row-start: 2;
    }

    .box9 {
        grid-column-start: 5;
        grid-row-start: 2;
    }

    .box10 {
        grid-column-start: 6;
        grid-row-start: 1;
    }

    .box11 {
        grid-column-start: 6;
        grid-row-start: 2;
    }

    .box12 {
        grid-column-start: 6;
        grid-row-start: 3;
    }

    .box13 {
        grid-column-start: 7;
        grid-row-start: 1;
    }

    .box14 {
        grid-column-start: 7;
        grid-row-start: 2;
    }

    .box15 {
        grid-column-start: 7;
        grid-row-start: 3;
    }

    .box16 {
        grid-column-start: 8;
        grid-row-start: 2;
    }
</style>